# Generated by Django 6.1.1 on 2026-09-25 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('server_type', models.CharField(choices=[('EBS', 'Oracle EBS (Direct DB)'), ('FUSION', 'Oracle Fusion Cloud')], default='EBS', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.IntegerField(default=1521)),
                ('service_name', models.CharField(blank=True, default='', max_length=255)),
                ('sid', models.CharField(blank=True, default='', max_length=255)),
                ('base_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DB Server',
                'verbose_name_plural': 'DB Servers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EbsQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=64)),
                ('sql_hash', models.CharField(db_index=True, help_text='SHA-256 hash of SQL (not raw SQL)', max_length=64)),
                ('sql_preview', models.CharField(help_text='First 300 chars of SQL (no credentials)', max_length=300)),
                ('rows_returned', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to='api.dbserver')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', '-created_at'], name='api_ebsquer_usernam_236499_idx'), models.Index(fields=['server', '-created_at'], name='api_ebsquer_server__411858_idx')],
            },
        ),
    ]
