/*
## TASK 0001 ##
## WHAT I NEED IN THIS TASK 
-1 GET EMP INFO 
-2 GET EMP SALARY 
3- GET DEPARTMENT 
4- JOBS FOR EATCH EVERY EMP 
*/
SELECT * FROM ALL_TABLES;
SELECT * FROM ALL_TABLES WHERE OWNER IS NOT NULL AND TABLE_NAME LIKE '%DEPART%'; -- PER_ALL_PEOPLE_F, PER_ALL_POSITIONS
SELECT * FROM HR_ALL_ORGANIZATION_UNITS ;

SELECT * FROM PER_ALL_PEOPLE_F ; --PERSON_ID , BUSINESS_GROUP_ID , EFFECTIVE_START_DATE , EFFECTIVE_END_DATE , NATIONALITY , SEX
SELECT * FROM PER_ALL_POSITIONS; -- POSITION_ID , BUSINESS_GROUP_ID , JOB_ID , DATE_EFFECTIVE , NAME , ORGANIZATION_ID
--SELECT * FROM BOM_DEPARTMENTS ;
SELECT * FROM PER_ALL_ASSIGNMENTS_F;
SELECT * FROM PAY_ALL_PAYROLLS_F; -- PAYROLL_ID , EFFECTIVE_END_DATE , EFFECTIVE_START_DATE ,BUSINESS_GROUP_ID , PAYROLL_NAME
SELECT * FROM PER_ALL_ASSIGNMENTS_F WHERE EFFECTIVE_END_DATE BETWEEN SYSDATE AND EFFECTIVE_END_DATE; -- BUSINESS_GROUP_ID , POSITION_ID , JOB_ID , ASSIGNMENT_ID , EFFECTIVE_END_DATE , PERSON_ID ,ORGANIZATION_ID , VACANCY_ID , MANAGER_FLAG  , SAL_REVIEW_PERIOD_FREQUENCY    POSITION_ID
SELECT * FROM PER_PAY_PROPOSALS ; --PROPOSED_SALARY_N , APPROVED(BOLEAN),DATE_TO - ASSIGNMENT_ID - PAY_PROPOSAL_ID , BUSINESS_GROUP_ID
SELECT * FROM PAY_ELEMENT_ENTRY_VALUES_F;-- INPUT_VALUE_ID, EFFECTIVE_END_DATE
SELECT * FROM PAY_RUN_RESULT_VALUES; -- RESULT_VALUE
SELECT * FROM HR_ALL_ORGANIZATION_UNITS ;
--- SALARY ---
SELECT * FROM PER_PAY_BASES ; -- PAY_BASIS_ID , BUSINESS_GROUP_ID , PAY_BASIS , --  WHERE SCREEN_ENTRY_VALUE IS NOT NULL ORDER BY 6 DESC;   
SELECT * FROM PER_PAY_PROPOSALS ; --PROPOSED_SALARY_N , PROPOSAL_REASON , PAY_PROPOSAL_ID
SELECT * FROM PER_PAY_PROPOSALS_V2 ; -- ASSIGNMENT_ID , PROPOSED_SALARY , PAY_PROPOSAL_ID
SELECT * FROM PER_ASSIGNMENTS_v2 WHERE ASSIGNMENT_ID = 566 ; -- PERSON_ID , PAYROLL_ID , SALARY_BASIS , STATUS , LOCATION_CODE , POSITION , JOB , PAYROLL , ASSIGNMENT_ID
SELECT * FROM ALL_TABLES WHERE TABLE_NAME LIKE '%PER%ASSI%'; --PER_ALL_ASSIGNMENTS_F
SELECT * FROM PER_PEOPLE_F;
--23-JUL-2000
--4,430.40000
--------------------------- START ------------------

--FUNCTION MAX   > MK_GET_MAX_SALARY_FN    DONE
--FUNCTION COUNT > MK_GET_COUNT_RECORD_FN  XXXXXXXXXXXX
--PAKAGE         > MK_ALL_EMPLOYEE_INFO_PK  DONE
--VIEW           > MK_ALL_EMPLOYEE_INFO_V   DONE
--PROCUDRE       > MK_GET_EMP_TOTAL_SALARIES_PROC DONE 
--------------------------------------------------


WITH MAIN_DATA AS ( 
SELECT 
    FU.USER_ID,
    FU.USER_NAME,
    PAPF.PERSON_ID                        EMPLOYEE_ID,
    PAPF.EMPLOYEE_NUMBER,            
    PAPF.FULL_NAME ,             
    PAPF.NATIONALITY ,           
    PAPF.SEX                              GENDER ,
    PAP.POSITION_ID ,            
    PAP.NAME                              POSITION_NAME,
    PAP.ORGANIZATION_ID ,
    HAOU.NAME ORG_NAME, 
    PAPAY.PAYROLL_ID ,
    PAPAY.PAYROLL_NAME ,
    PPP.PAY_PROPOSAL_ID ,
    PPP.PROPOSED_SALARY_N                 BASIC_SALARY ,
    PPP.PROPOSAL_REASON,             
    PPP.CHANGE_DATE                       SALARY_CHANGE_DATE,
    PAV.EFFECTIVE_START_DATE , 
    PAV.LOCATION_CODE ,
    PAV.POSITION ,
    PAV.PAYROLL,
    PPF.NATIONAL_IDENTIFIER               NATIONAL_ID,
    ROUND (MK_GET_MAX_SALARY_FN(PAPF.PERSON_ID))  MAX_SALARY ,

    
    ROW_NUMBER() OVER ( PARTITION BY FU.USER_ID ORDER BY PPP.PAY_PROPOSAL_ID DESC ) ROW_N
    
        
FROM       PER_ALL_PEOPLE_F                     PAPF        ----- MAIN 

INNER JOIN PER_PEOPLE_F                         PPF          ON PAPF.PERSON_ID = PPF.PERSON_ID

INNER JOIN FND_USER                             FU           ON FU.EMPLOYEE_ID = PAPF.PERSON_ID

INNER JOIN PER_ALL_ASSIGNMENTS_F                PASF         ON PASF.PERSON_ID = PAPF.PERSON_ID
                                                            AND TRUNC(SYSDATE) BETWEEN PASF.EFFECTIVE_START_DATE AND PASF.EFFECTIVE_END_DATE


LEFT OUTER JOIN PER_ALL_POSITIONS               PAP          ON PAP.POSITION_ID = PASF.POSITION_ID
                                                            AND PAP.DATE_EFFECTIVE =  TRUNC(SYSDATE) --PASF.EFFECTIVE_START_DATE
                                                               
LEFT OUTER JOIN HR_ALL_ORGANIZATION_UNITS       HAOU         ON HAOU.ORGANIZATION_ID = PAP.ORGANIZATION_ID       

LEFT OUTER JOIN PAY_ALL_PAYROLLS_F              PAPAY        ON PAPAY.BUSINESS_GROUP_ID = PAPF.BUSINESS_GROUP_ID 
                                                            AND TRUNC(SYSDATE) BETWEEN PAPAY.EFFECTIVE_START_DATE AND PAPAY.EFFECTIVE_END_DATE
    
LEFT OUTER JOIN PER_ASSIGNMENTS_v2              PAV          ON PAV.PERSON_ID = PAPF.PERSON_ID
                                                            AND PAV.ASSIGNMENT_ID IS NOT NULL

LEFT OUTER JOIN PER_PAY_PROPOSALS               PPP          ON PPP.ASSIGNMENT_ID = PASF.ASSIGNMENT_ID   
                                                            AND PPP.APPROVED = 'Y'


WHERE 1 = 1 
AND PPF.CURRENT_EMPLOYEE_FLAG = 'Y'
AND PPP.CHANGE_DATE <= TRUNC(SYSDATE)
AND PAPF.EMPLOYEE_NUMBER  = TRIM(NVL(:P_EMPLOYEE_NUMBER,PAPF.EMPLOYEE_NUMBER) )                        
   --:P_USER_ID 1001232 > AND PAPF.PERSON_ID = 3840 > EMP_NUMBER = 364
)
SELECT * 
FROM MAIN_DATA
WHERE ROW_N = 1 -- FOR ROW_NUMBER 




