/*
CREATE PACKAGE FOR HR_TASK_0001
*/
CREATE OR REPLACE PACKAGE MK_ALL_EMPLOYEE_INFO_PK IS 

    FUNCTION MK_GET_MAX_SALARY_FN (
        P_PERSON_ID IN NUMBER
    ) RETURN NUMBER;
    
    
PROCEDURE MK_GET_EMP_TOTAL_SALARIES_PROC (
        P_PERSON_ID   IN  NUMBER, 
        P_TOTAL_SAL   OUT NUMBER 
    ) ;
        
END MK_ALL_EMPLOYEE_INFO_PK;
