CREATE OR REPLACE VIEW MK_ALL_EMPLOYEE_INFO_V AS

SELECT 
    FU.USER_ID,
    FU.USER_NAME,
    PAPF.PERSON_ID           EMPLOYEE_ID,
    PAPF.EMPLOYEE_NUMBER,
    PAPF.FULL_NAME ,
    PAPF.NATIONALITY ,
    PAPF.SEX                 GENDER ,
    PAP.POSITION_ID ,
    PAP.NAME                 POSITION_NAME,
    PAP.ORGANIZATION_ID ,
    HAOU.NAME ORG_NAME, 
    PAPAY.PAYROLL_ID ,
    PAPAY.PAYROLL_NAME ,
    PPP.PAY_PROPOSAL_ID ,
    PPP.PROPOSED_SALARY_N    BASIC_SALARY ,
    PPP.PROPOSAL_REASON,
    PPP.CHANGE_DATE          SALARY_CHANGE_DATE,
    PAV.EFFECTIVE_START_DATE , 
    PAV.LOCATION_CODE ,
    PAV.POSITION ,
    PAV.PAYROLL,
    PPF.NATIONAL_IDENTIFIER  NATIONAL_ID,
    
    ROW_NUMBER() OVER ( PARTITION BY FU.USER_ID ORDER BY PPP.PAY_PROPOSAL_ID DESC ) ROW_N
    
        
FROM       PER_ALL_PEOPLE_F                     PAPF        ----- MAIN 

INNER JOIN PER_PEOPLE_F                         PPF          ON PAPF.PERSON_ID = PPF.PERSON_ID

INNER JOIN FND_USER                             FU           ON FU.EMPLOYEE_ID = PAPF.PERSON_ID

INNER JOIN PER_ALL_ASSIGNMENTS_F                PASF         ON PASF.PERSON_ID = PAPF.PERSON_ID
                                                            AND TRUNC(SYSDATE) BETWEEN PASF.EFFECTIVE_START_DATE AND PASF.EFFECTIVE_END_DATE


LEFT OUTER JOIN PER_ALL_POSITIONS               PAP          ON PAP.POSITION_ID = PASF.POSITION_ID
                                                            AND PAP.DATE_EFFECTIVE =  TRUNC(SYSDATE) --PASF.EFFECTIVE_START_DATE
                                                               
LEFT OUTER JOIN HR_ALL_ORGANIZATION_UNITS       HAOU         ON HAOU.ORGANIZATION_ID = PAP.ORGANIZATION_ID       

LEFT OUTER JOIN PAY_ALL_PAYROLLS_F              PAPAY        ON PAPAY.BUSINESS_GROUP_ID = PAPF.BUSINESS_GROUP_ID 
                                                            AND TRUNC(SYSDATE) BETWEEN PAPAY.EFFECTIVE_START_DATE AND PAPAY.EFFECTIVE_END_DATE
    
LEFT OUTER JOIN PER_ASSIGNMENTS_v2              PAV          ON PAV.PERSON_ID = PAPF.PERSON_ID
                                                            AND PAV.ASSIGNMENT_ID IS NOT NULL

LEFT OUTER JOIN PER_PAY_PROPOSALS               PPP          ON PPP.ASSIGNMENT_ID = PASF.ASSIGNMENT_ID   
                                                            AND PPP.APPROVED = 'Y'


WHERE 1 = 1 
AND PPF.CURRENT_EMPLOYEE_FLAG = 'Y'
AND PPP.CHANGE_DATE <= TRUNC(SYSDATE)
                       


;
SELECT * FROM MK_ALL_EMPLOYEE_INFO_V ; -- ## FOR CHECK VIEW  