CREATE OR REPLACE PACKAGE BODY MK_ALL_EMPLOYEE_INFO_PK IS 

-- ## FIRST FUNCTION RETURN MAX SALARY 
    FUNCTION MK_GET_MAX_SALARY_FN (
        P_PERSON_ID IN NUMBER
        ) RETURN NUMBER IS
        V_MAX_SALARY NUMBER;
    BEGIN
        SELECT MAX(PPP.PROPOSED_SALARY_N)
        INTO V_MAX_SALARY
        FROM PER_ALL_ASSIGNMENTS_F      PAAF
        INNER JOIN PER_PAY_PROPOSALS    PPP     ON PPP.ASSIGNMENT_ID = PAAF.ASSIGNMENT_ID
        
        WHERE PAAF.PERSON_ID = P_PERSON_ID
          AND PAAF.PRIMARY_FLAG = 'Y'
          AND PPP.APPROVED = 'Y'
          AND PPP.CHANGE_DATE <= TRUNC(SYSDATE);
        RETURN NVL(V_MAX_SALARY, 0);
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
    END MK_GET_MAX_SALARY_FN;
    
    PROCEDURE MK_GET_EMP_TOTAL_SALARIES_PROC (
        P_PERSON_ID   IN  NUMBER, 
        P_TOTAL_SAL   OUT NUMBER 
    ) IS
    BEGIN
        SELECT NVL(ROUND(SUM(PPP.PROPOSED_SALARY_N), 2), 0) TOTAL_PAYMENT_FROM_START
        INTO   P_TOTAL_SAL
        FROM   PER_ALL_PEOPLE_F             PAPF
        INNER JOIN PER_ALL_ASSIGNMENTS_F    PAAF   ON PAPF.PERSON_ID = PAAF.PERSON_ID
        INNER JOIN PER_PAY_PROPOSALS        PPP    ON PPP.ASSIGNMENT_ID = PAAF.ASSIGNMENT_ID
        WHERE 1=1 ;
    EXCEPTION
        WHEN OTHERS THEN
            P_TOTAL_SAL := 0;
    END MK_GET_EMP_TOTAL_SALARIES_PROC;
  

END MK_ALL_EMPLOYEE_INFO_PK ; 


