# Generated by Django 6.1.1 on 2026-09-25 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dbserver_ebsquerylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='editor_case',
            field=models.CharField(default='upper', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='editor_theme',
            field=models.CharField(default='vs-dark', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ebsquerylog',
            name='sql_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='ebsquerylog',
            name='sql_preview',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('CONSULTANT', 'Consultant'), ('USER', 'Standard User')], default='USER', max_length=20),
        ),
        migrations.CreateModel(
            name='EditorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Session', max_length=255)),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('editor_sql', models.TextField(blank=True, default='')),
                ('server_id', models.IntegerField(blank=True, null=True)),
                ('db_username', models.CharField(blank=True, default='', max_length=255)),
                ('theme', models.CharField(default='vs-dark', max_length=30)),
                ('case_mode', models.CharField(default='upper', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('closed', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user', models.CharField(blank=True, db_index=True, default='', help_text='Specific user (leave empty for broadcast)', max_length=64)),
                ('target_role', models.CharField(choices=[('ALL', 'Everyone'), ('ADMIN', 'Admins only'), ('CONSULTANT', 'Consultants only'), ('USER', 'Standard users only')], db_index=True, default='ALL', help_text='Broadcast to all users with this role', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('level', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Error')], default='info', max_length=20)),
                ('icon', models.CharField(default='fa-bell', max_length=50)),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('link_label', models.CharField(blank=True, default='', max_length=100)),
                ('action_type', models.CharField(blank=True, default='', help_text='e.g. access_request, ebs_fail, upload', max_length=50)),
                ('action_ref', models.CharField(blank=True, default='', help_text='Reference to the object (dataset name, etc.)', max_length=255)),
                ('read_by', models.TextField(blank=True, default='', help_text='Comma-separated usernames who marked as read')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_user', '-created_at'], name='api_notific_target__a1d8ee_idx'), models.Index(fields=['target_role', '-created_at'], name='api_notific_target__7418f9_idx')],
            },
        ),
    ]
